# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c68f0471c3e8ae3b7551db0b5d856e8f5aa4ee798710318b8b5808b60cff4ae12361e1256fa068ea215ad80d53ca12978e397535904218a4cfd0940cb6c37714

test:
  secret_key_base: dbd371af71e662bffbe2676dfee69bdd83d984c21950e10889203b2cc97487c78d8ae51af6579f367f8d7216f4c3605aed31e535e7311e3410325dede76fae3d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
